[pytest]
python_files = *_tests.py test_*.py
python_classes = Test*
python_functions = test_*

markers = 
    courses: Маркировки для тестов, связанных с курсами
    regression: Маркировки для регрессионных тестов