app_url=https://nikita-filonov.github.io/qa-automation-engineer-ui-course
headless=False
browsers=[<Browser.CHROMIUM: 'chromium'>]
test_user={'email': 'user.name@gmail.com', 'username': 'username', 'password': 'password'}
test_data={'image_png_file': WindowsPath('testdata/files/image.png')}
videos_dir=videos
tracing_dir=tracing
allure_results_dir=allure-results
browser_state_file=browser-state.json
os_info=Windows, 11
python_version=3.14.2 (tags/v3.14.2:df79316, Dec  5 2025, 17:18:21) [MSC v.1944 64 bit (AMD64)]